#!/usr/bin/python3
def raise_exception():
    proposition = [1, 'think']
    result = proposition[0] + proposition[1]
    return result
